import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../domain/entities/service_request_entity.dart';
import '../../domain/entities/service_response_entity.dart';
import '../../domain/repositories/service_response_repository.dart';
import 'auth_controller.dart';

class OfferController extends GetxController {
  final ServiceResponseRepository _responseRepository;
  final AuthController _authController = Get.find<AuthController>();

  OfferController(this._responseRepository);

  final messageController = TextEditingController();
  final priceController = TextEditingController();
  final RxBool isLoading = false.obs;

  Future<void> submitOffer(ServiceRequestEntity request) async {
    if (messageController.text.trim().isEmpty || priceController.text.trim().isEmpty) {
      Get.snackbar('Error', 'Please enter a message and price');
      return;
    }

    final provider = _authController.currentUser.value;
    if (provider == null) return;

    isLoading.value = true;
    try {
      final response = ServiceResponseEntity(
        id: '', // Generated by Repo
        requestId: request.id,
        providerId: provider.id,
        providerName: provider.name,
        providerProfileImage: provider.profileImage,
        message: messageController.text.trim(),
        price: double.tryParse(priceController.text.trim()) ?? 0.0,
        timestamp: DateTime.now(),
        status: 'pending',
      );

      await _responseRepository.submitResponse(response);
      
      Get.back(); // Close modal
      Get.snackbar('Success', 'Your offer has been sent to the customer!');
    } catch (e) {
      Get.snackbar('Error', 'Failed to send offer: $e');
    } finally {
      isLoading.value = false;
    }
  }

  @override
  void onClose() {
    messageController.dispose();
    priceController.dispose();
    super.onClose();
  }
}
